#! /bin/bash

while read line
do
        equipo=$(echo $line | cut -d  "," -f1 | tr -d '"')
	tipo=$(echo $line | cut -d "," -f2 | tr -d '"')
	echo "TIPO: $tipo"
	echo "LINEA: $line"
	echo "EQUIPO: $equipo"


##################################################################################################
#Chequear IP

	ip=$(host $equipo | awk '{ print $4}')

##################################################################################################

#Chequear Modelo

        a=$(snmpwalk -v 2c -c n0ucpchu3 $equipo .1.3.6.1.2.1.47.1.1.1.1.13.1001  | awk '{ print $4}')
   

#Chequeo en caso que el modelo sea cisco


	if [ "$a" == "Such"  ]; then
       		b=$(snmpwalk -v 2c -c n0ucpchu3 $equipo .1.3.6.1.4.1.9.5.1.2.19 | awk '{ print $4}')

		a=$b

	


#Chequeo en caso que el modelo sea cisco 2


	elif [ "$a" == ""  ]; then
       		c=$(snmpwalk -v 2c -c n0ucpchu3 $equipo .1.3.6.1.2.1.47.1.1.1.1.13.1 | awk '{ print $4}')

		a=$c

	

#Chequeo en caso que el modelo sea Alcatel 


#	else 
#	if [ "$a" == "Such"  ]; then
 #      	d=$(snmpwalk -v 2c -c n0ucpchu3 $line .1.3.6.1.4.1.6527.3.1.2.2.1.8.1.8  | awk '{ print $4}')

#		a=$d

#	fi
	fi






##################################################################################################

#Chequear Serial

        f=$(snmpwalk -v 2c -c n0ucpchu3 $equipo .1.3.6.1.2.1.47.1.1.1.1.11.1   | awk '{ print $4}')
   

#Chequeo en caso que el Serial sea cisco


	if [ "$f" == "Such"  ]; then
       		g=$(snmpwalk -v 2c -c n0ucpchu3 $equipo .1.3.6.1.4.1.9.5.1.2.19 | awk '{ print $4}')

		f=$g

	



	fi



##################################################################################################


#Chequear Descripcion

        h=$(snmpwalk -v 2c -c n0ucpchu3 $equipo sysLocation.0   | awk  '{ print $4" "$5" "$6" "$7" "$5" "$6}')

#h=$(snmpwalk -v 2c -c n0ucpchu3 $line sysLocation.0   | awk -F"," '{ print $4$5$6$7$5$6}')
# | awk ''FS=","( print $4$5$6$7$8$9$10}')

##################################################################################################



        algo="$equipo,$tipo,$ip,$a,$f,'$h'"
        echo $algo | tr -d '"' >> equipos_resultado.txt
done < equipos.csv

